name: EPDM
on: workflow_dispatch
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Restore dependencies
            run: dotnet restore aspnet-get-started/aspnet-get-started.csproj
          - name: Build
            run: dotnet build --no-restore
