name: EPDM
on: workflow_dispatch
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: "actions/checkout@v3"
            - name: restore
              run: dotnet restore "aspnet-get-started/aspnet-get-started.csproj"
            - name: build
              run: dotnet build "aspnet-get-started/aspnet-get-started.csproj"